version: '3'

services:
    wsgi:
        image: elifesciences/digests:${IMAGE_TAG}
        command: >
            bash -c "./migrate.sh && exec venv/bin/newrelic-admin run-program venv/bin/uwsgi --ini=/srv/digests/uwsgi.ini --enable-threads"
        volumes:
            - /srv/digests/uwsgi.ini:/srv/digests/uwsgi.ini
            - /srv/digests/var/logs:/srv/digests/var/logs
        networks:
            - default
            - databases
        ports:
            - 9000:9000
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/digests/containers.env
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    default:
    databases:
        external: true
