version: '3'

services:
    wsgi:
        image: elifesciences/digests:${IMAGE_TAG}
        #command: venv/bin/newrelic-admin run-program venv/bin/uwsgi --ini=/srv/digests/uwsgi.ini
        command: venv/bin/uwsgi --ini=/srv/digests/uwsgi.ini
        volumes:
            - /srv/digests/app.cfg:/srv/digests/app.cfg
            - /srv/digests/uwsgi.ini:/srv/digests/uwsgi.ini
            - /srv/digests/var/logs:/srv/digests/var/logs
        networks:
            - default
            #- databases
        ports:
            - 9000:9000
        env_file:
            - /home/{{ pillar.elife.deploy_user.username }}/digests/containers.env
        restart: always

networks:
    default:
    #databases:
    #    external: true
